// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjEsAEffOHi17GOcvEnh26gTAEwgQszQ',
    appId: '1:526180610767:web:0fcbf9fd3efd3810bffdba',
    messagingSenderId: '526180610767',
    projectId: 'flutter-app-ec8dd',
    authDomain: 'flutter-app-ec8dd.firebaseapp.com',
    databaseURL: 'https://flutter-app-ec8dd.firebaseio.com',
    storageBucket: 'flutter-app-ec8dd.appspot.com',
    measurementId: 'G-1G9Y1N3MSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYoQY15UhzToO0uYGKmppdEcp1o0FGEGA',
    appId: '1:526180610767:android:b3914abb4070ec3fbffdba',
    messagingSenderId: '526180610767',
    projectId: 'flutter-app-ec8dd',
    databaseURL: 'https://flutter-app-ec8dd.firebaseio.com',
    storageBucket: 'flutter-app-ec8dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGT4PW5cPpk3mQJkepavD41b8ArSz9CU',
    appId: '1:526180610767:ios:552a2f6ed678d2f7bffdba',
    messagingSenderId: '526180610767',
    projectId: 'flutter-app-ec8dd',
    databaseURL: 'https://flutter-app-ec8dd.firebaseio.com',
    storageBucket: 'flutter-app-ec8dd.appspot.com',
    androidClientId: '526180610767-c20bio3mvfva7nb9k994qno8erif1r4v.apps.googleusercontent.com',
    iosClientId: '526180610767-q3sip9vcbchpa6q2p0rlno2vb8imbfa7.apps.googleusercontent.com',
    iosBundleId: 'com.pingak9.template.stg',
  );
}
