// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2BCio3JP3CIRXfmfs0kuW7wUSboEKVI',
    appId: '1:535789737885:web:08771737097b8c6480c174',
    messagingSenderId: '535789737885',
    projectId: 'template-app-prod-3a034',
    authDomain: 'template-app-prod-3a034.firebaseapp.com',
    storageBucket: 'template-app-prod-3a034.appspot.com',
    measurementId: 'G-XV064MGKGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9JLZxQb6qh6Lzs9OJ6GhQxN4FDirna2s',
    appId: '1:535789737885:android:62e3b967ff87599480c174',
    messagingSenderId: '535789737885',
    projectId: 'template-app-prod-3a034',
    storageBucket: 'template-app-prod-3a034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJcmNBow0YS4BVADc-K3aDLjvZW9DUMR8',
    appId: '1:535789737885:ios:58d9a69f9dfa23bf80c174',
    messagingSenderId: '535789737885',
    projectId: 'template-app-prod-3a034',
    storageBucket: 'template-app-prod-3a034.appspot.com',
    iosClientId: '535789737885-n14bfdlqb726ht8lte1he0b9ilpj3c0i.apps.googleusercontent.com',
    iosBundleId: 'com.pingak9.template',
  );
}
