# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

aabPath = '../build/app/outputs/bundle/release/app-release.aab'
apkPath = '../build/app/outputs/apk/release/app-release.apk'
firebaseAppID = '1:526180610767:android:ae2be982eaabbf74bffdba'

default_platform(:android)

platform :android do
  desc "Submit a new beta build to Google Play"
  lane :beta do
    sh "flutter build appbundle -v"
    upload_to_play_store(
      track: 'internal', # production, beta, alpha, internal
      aab: aabPath,
      # release_status: 'draft',  # Remove after enable beta
    )
  end

  desc "Deploy with Firebase"
  lane :firebase do
    sh "flutter build apk --release"
    # This project is not linked to a Google Play account.
    firebase_app_distribution(
      app: firebaseAppID,
      testers: "jimmy.to.goldenowl@gmail.com",
      groups: "Tester",
      release_notes: sh("git log -10 --pretty='%s'"),
      android_artifact_path: apkPath,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end

end
